version: "3.9"

services:
  db_alumnos:
    image: mysql:8.0
    container_name: db_alumnos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alumnos
      MYSQL_USER: alumnos_user
      MYSQL_PASSWORD: alumnos_password
    volumes:
      - db_alumnos_data:/var/lib/mysql
      - ./alumnos.sql:/docker-entrypoint-initdb.d/alumnos.sql


  Tec_maestros:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maestros
      MYSQL_USER: maestros_user
      MYSQL_PASSWORD: maestros_password
    volumes:
      - db_maestros_data:/var/lib/mysql
      - ./maestros.sql:/docker-entrypoint-initdb.d/maestros.sql


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1  # Permite conectar con cualquier contenedor MySQL
    ports:
      - "8080:80"


  app_alumnos:
    build:
      context: .
      dockerfile: dockerfile_alumnos.yaml
    container_name: app_alumnos
    environment:
      DB_HOST: db_alumnos
      DB_NAME: alumnos
      DB_USER: alumnos_user
      DB_PASSWORD: alumnos_password
    ports:
      - "8081:80"


  app_maestros:
    build:
      context: .
      dockerfile: dockerfile_maestros.yaml
    container_name: app_maestros
    restart: always
    environment:
      DB_HOST: Tec_maestros
      DB_NAME: maestros
      DB_USER: maestros_user
      DB_PASSWORD: maestros_password
      API_ALUMNO: app_alumnos
    ports:
      - "8082:80"


volumes:
  db_alumnos_data:
  db_maestros_data:

